apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: liliiakoloda/spring-petclinic:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
